In [1]:
from time import time
from pathlib import Path
import numpy as np
from scipy.io import loadmat
from numpy.testing import assert_array_almost_equal, assert_array_equal

from clinica_surfstat import clinica_surfstat
from _inputs import _get_t1_freesurfer_custom_file_template

In [2]:
caps_dir = Path(
    #"/network/lustre/iss02/aramis/project/clinica/data_ci/StatisticsSurface"
    "/Users/nicolas.gensollen/GitRepos/clinica_data_ci/data_ci/StatisticsSurface"
)
input_dir = caps_dir / Path("in/caps/subjects")
output_dir = Path("./out")
tsv_file = caps_dir / Path("in/subjects.tsv")
freesurfer_home = Path("/Applications/freesurfer/7.2.0/")
surface_file = _get_t1_freesurfer_custom_file_template(input_dir)
ground_truth_dir = Path("/Users/nicolas.gensollen/ground_truth/statistics-surface/group-UnitTest/")

## 1. Group comparison : Male vs Female

In [3]:
start = time()
design_matrix = "1 + sex"
contrast = "sex"
glm_type = "group_comparison"
group_label = "Male-vs-Female"
feature_label = "ct"
parameters = dict()
clinica_surfstat(
    input_dir,
    output_dir,
    tsv_file,
    design_matrix,
    contrast,
    glm_type,
    group_label,
    freesurfer_home,
    surface_file,
    feature_label,
    parameters,
    verbose=True,
)
print(f"--> Computations took {time() - start} seconds...")

--> fsaverage path : /Applications/freesurfer/7.2.0/subjects/fsaverage/surf


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_inputs.py:122: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  combined = np.vstack(parts)


--> The GLM linear model is: 1 + sex
--> The GLM type is: group_comparison
--> Fitting the SLM model with contrast Female-lt-Male...
--> Writing results to JSON in out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_results.json...
--> Writing results to mat files...
--> Saving matrix to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_coefficients.mat
--> Saving matrix to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_TStatistics.mat
--> Saving matrix to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_uncorrectedPValue.mat
--> Saving matrix to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_FDR.mat
--> Saving matrix to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20_correctedPValue.mat


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_outputs.py:98: UserWarning: Writing results to BIDS is not implemented yet.
  warnings.warn("Writing results to BIDS is not implemented yet.")


--> Saving plot to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20TStatistics.png
--> Saving plot to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20uncorrectedPValue.png
--> Saving plot to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20FDR.png
--> Saving plot to out/group-Male-vs-Female_Female-lt-Male_measure-ct_fwhm-20correctedPValue.png
########################################
After correction (Clusterwise Correction for Multiple Comparisons): 
   clusid  nverts    resels         P
0       1    24.0  1.468718  0.474061
1       2    82.0  1.432200  0.491796
2       3     7.0  0.635045  0.962500
Clusters found: 3
Significative clusters (after correction): 0
--> Fitting the SLM model with contrast Male-lt-Female...
--> Writing results to JSON in out/group-Male-vs-Female_Male-lt-Female_measure-ct_fwhm-20_results.json...
--> Writing results to mat files...
--> Saving matrix to out/group-Male-vs-Female_Male-lt-Female_measure-ct_fwhm-20_coefficients.mat
--> 

/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_outputs.py:98: UserWarning: Writing results to BIDS is not implemented yet.
  warnings.warn("Writing results to BIDS is not implemented yet.")


--> Saving plot to out/group-Male-vs-Female_Male-lt-Female_measure-ct_fwhm-20uncorrectedPValue.png
--> Saving plot to out/group-Male-vs-Female_Male-lt-Female_measure-ct_fwhm-20FDR.png
--> Saving plot to out/group-Male-vs-Female_Male-lt-Female_measure-ct_fwhm-20correctedPValue.png
########################################
After correction (Clusterwise Correction for Multiple Comparisons): 
Empty DataFrame
Columns: [clusid, nverts, resels, P]
Index: []
Clusters found: 0
Significative clusters (after correction): 0
--> Computations took 177.70107412338257 seconds...


## 2. Group comparison: AD vs CN with covariates age and sex 

In [4]:
start = time()
design_matrix = "1 + group + age + sex"
contrast = "group"
glm_type = "group_comparison"
group_label = "AD-vs-CN"
feature_label = "ct"
parameters = dict()
clinica_surfstat(
    input_dir,
    output_dir,
    tsv_file,
    design_matrix,
    contrast,
    glm_type,
    group_label,
    freesurfer_home,
    surface_file,
    feature_label,
    parameters,
    verbose=True,
)
print(f"--> Computations took {time() - start} seconds...")

--> fsaverage path : /Applications/freesurfer/7.2.0/subjects/fsaverage/surf


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_inputs.py:122: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  combined = np.vstack(parts)


--> The GLM linear model is: 1 + group + age + sex
--> The GLM type is: group_comparison
--> Fitting the SLM model with contrast AD-lt-CN...
--> Writing results to JSON in out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_results.json...
--> Writing results to mat files...
--> Saving matrix to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_coefficients.mat
--> Saving matrix to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_TStatistics.mat
--> Saving matrix to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_uncorrectedPValue.mat
--> Saving matrix to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_FDR.mat
--> Saving matrix to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_correctedPValue.mat
--> Saving plot to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20TStatistics.png


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_outputs.py:98: UserWarning: Writing results to BIDS is not implemented yet.
  warnings.warn("Writing results to BIDS is not implemented yet.")


--> Saving plot to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20uncorrectedPValue.png
--> Saving plot to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20FDR.png
--> Saving plot to out/group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20correctedPValue.png
########################################
After correction (Clusterwise Correction for Multiple Comparisons): 
    clusid  nverts    resels         P
0        1   239.0  8.452505  0.085621
1        2    30.0  1.923901  0.457488
2        3    14.0  1.733303  0.507004
3        4    93.0  1.031970  0.767603
4        5    17.0  0.691147  0.921419
5        6    76.0  0.593710  0.956412
6        7     5.0  0.415081  0.993804
7        8    13.0  0.401075  0.995119
8        9    12.0  0.300342  0.999588
9       10    19.0  0.036456  1.000000
10      11     5.0  0.018095  1.000000
Clusters found: 11
Significative clusters (after correction): 0
--> Fitting the SLM model with contrast CN-lt-AD...
--> Writing results to JSON in out/group-AD-vs-CN_CN-lt-AD_me

/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_outputs.py:98: UserWarning: Writing results to BIDS is not implemented yet.
  warnings.warn("Writing results to BIDS is not implemented yet.")


--> Saving plot to out/group-AD-vs-CN_CN-lt-AD_measure-ct_fwhm-20uncorrectedPValue.png
--> Saving plot to out/group-AD-vs-CN_CN-lt-AD_measure-ct_fwhm-20FDR.png
--> Saving plot to out/group-AD-vs-CN_CN-lt-AD_measure-ct_fwhm-20correctedPValue.png
########################################
After correction (Clusterwise Correction for Multiple Comparisons): 
   clusid  nverts    resels         P
0       1     8.0  2.051748  0.428337
1       2    44.0  1.559541  0.559422
2       3     1.0  0.120314  1.000000
Clusters found: 3
Significative clusters (after correction): 0
--> Computations took 218.0976800918579 seconds...


### Test against reference

Test the results against the reference obtained with Clinica (non regression tests).
Note that contrast names are reversed due to an error in the current Matlab code in Clinica.

#### Check T-statistics

In [5]:
ref = loadmat(
    str(ground_truth_dir / "group-UnitTest_AD-lt-CN_measure-ct_fwhm-20_TStatistics.mat")
)["tvaluewithmask"]
ref

array([[0.35022361, 2.92066357, 4.25501375, ..., 1.89603155, 1.89405874,
        1.89662065]])

In [6]:
computed = loadmat(
    str(output_dir / "group-AD-vs-CN_CN-lt-AD_measure-ct_fwhm-20_TStatistics.mat")
)["tvaluewithmask"]
computed

array([[0.35022361, 2.92066357, 4.25501375, ..., 1.89603155, 1.89405874,
        1.89662065]])

In [7]:
assert_array_almost_equal(ref, computed)

In [8]:
ref = loadmat(
    str(ground_truth_dir / "group-UnitTest_CN-lt-AD_measure-ct_fwhm-20_TStatistics.mat")
)["tvaluewithmask"]
ref

array([[-0.35022361, -2.92066357, -4.25501375, ..., -1.89603155,
        -1.89405874, -1.89662065]])

In [9]:
computed = loadmat(
    str(output_dir / "group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_TStatistics.mat")
)["tvaluewithmask"]
computed

array([[-0.35022361, -2.92066357, -4.25501375, ..., -1.89603155,
        -1.89405874, -1.89662065]])

In [10]:
assert_array_almost_equal(ref, computed)

### Check model coefficients

In [11]:
ref = loadmat(
    str(ground_truth_dir / "group-UnitTest_CN-lt-AD_measure-ct_fwhm-20_coefficients.mat")
)["to_save"]
ref

array([[ 1.12288808e+00,  9.94678508e-01,  1.82439934e+00, ...,
         2.43419350e+00,  2.43246687e+00,  2.42990568e+00],
       [ 5.21811440e-01,  2.98611697e-01,  7.68132891e-01, ...,
         9.04206283e-01,  9.06807860e-01,  9.08709725e-01],
       [ 6.01076636e-01,  6.96066811e-01,  1.05626645e+00, ...,
         1.52998722e+00,  1.52565901e+00,  1.52119595e+00],
       [ 2.60883119e-03,  2.30871138e-03, -1.98140653e-02, ...,
        -3.19322330e-02, -3.19659106e-02, -3.19554695e-02],
       [ 4.27840752e-01,  4.46792347e-01,  8.84694488e-01, ...,
         1.25112207e+00,  1.25298655e+00,  1.25363383e+00],
       [ 6.95047324e-01,  5.47886161e-01,  9.39704855e-01, ...,
         1.18307143e+00,  1.17948032e+00,  1.17627185e+00]])

In [12]:
computed = loadmat(
    str(output_dir / "group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_coefficients.mat")
)["coef"]
computed

array([[ 1.12288808e+00,  9.94678508e-01,  1.82439934e+00, ...,
         2.43419350e+00,  2.43246687e+00,  2.42990568e+00],
       [ 5.21811440e-01,  2.98611697e-01,  7.68132891e-01, ...,
         9.04206283e-01,  9.06807860e-01,  9.08709725e-01],
       [ 6.01076636e-01,  6.96066811e-01,  1.05626645e+00, ...,
         1.52998722e+00,  1.52565901e+00,  1.52119595e+00],
       [ 2.60883119e-03,  2.30871138e-03, -1.98140653e-02, ...,
        -3.19322330e-02, -3.19659106e-02, -3.19554695e-02],
       [ 4.27840752e-01,  4.46792347e-01,  8.84694488e-01, ...,
         1.25112207e+00,  1.25298655e+00,  1.25363383e+00],
       [ 6.95047324e-01,  5.47886161e-01,  9.39704855e-01, ...,
         1.18307143e+00,  1.17948032e+00,  1.17627185e+00]])

In [13]:
assert_array_almost_equal(computed, ref)

### Check uncorrected P-values

In [14]:
ref = loadmat(
    str(ground_truth_dir / "group-UnitTest_CN-lt-AD_measure-ct_fwhm-20_uncorrectedPValue.mat")
)["uncorrectedpvaluesstruct"]
ref

array([[(array([[0.6253412 , 0.96926845, 0.98810175, ..., 0.92288309, 0.92273287,
                0.92292788]]), array([[1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[0.001]]))]],
      dtype=[('P', 'O'), ('mask', 'O'), ('thresh', 'O')])

In [15]:
computed = loadmat(
    str(output_dir / "group-AD-vs-CN_AD-lt-CN_measure-ct_fwhm-20_uncorrectedPValue.mat")
)["uncorrectedpvaluesstruct"]
computed

array([[(array([[0.6253412 , 0.96926845, 0.98810175, ..., 0.92288309, 0.92273287,
                0.92292788]]), array([[1, 1, 1, ..., 1, 1, 1]], dtype=uint8), array([[0.001]]))]],
      dtype=[('P', 'O'), ('mask', 'O'), ('thresh', 'O')])

In [16]:
assert_array_equal(ref['thresh'], computed['thresh'])

In [17]:
assert_array_equal(ref['mask'][0, 0], computed['mask'][0, 0])

In [18]:
assert_array_almost_equal(ref['P'][0, 0], computed['P'][0, 0])

### Check FDR

In [19]:
ref = loadmat(
    str(ground_truth_dir / "group-UnitTest_AD-lt-CN_measure-ct_fwhm-20_FDR.mat")
)["qvaluesstruct"]
ref

array([[(array([[0.74244736, 0.3869886 , 0.3862974 , ..., 0.43233187, 0.43240383,
                0.43227164]]), array([[1, 1, 1, ..., 1, 1, 1]], dtype=uint8))    ]],
      dtype=[('Q', 'O'), ('mask', 'O')])

In [20]:
computed = loadmat(
    str(output_dir / "group-AD-vs-CN_CN-lt-AD_measure-ct_fwhm-20_FDR.mat")
)["FDR"]
computed

array([[0.74244736, 0.3869886 , 0.3862974 , ..., 0.43233187, 0.43240383,
        0.43227164]])

In [21]:
assert_array_almost_equal(ref["Q"][0, 0], computed)

## 3. Correlation

In [22]:
start = time()
design_matrix = "1 + group + age + sex"
contrast = "age"
glm_type = "correlation"
group_label = "UnitTest"
feature_label = "ct"
parameters = dict()
clinica_surfstat(
    input_dir,
    output_dir,
    tsv_file,
    design_matrix,
    contrast,
    glm_type,
    group_label,
    freesurfer_home,
    surface_file,
    feature_label,
    parameters,
    verbose=True,
)
print(f"--> Computations took {time() - start} seconds...")

--> fsaverage path : /Applications/freesurfer/7.2.0/subjects/fsaverage/surf
--> The GLM linear model is: 1 + group + age + sex
--> The GLM type is: correlation
--> Fitting the SLM model with contrast age...


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_inputs.py:122: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  combined = np.vstack(parts)


--> Writing results to JSON in out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_results.json...
--> Writing results to mat files...
--> Saving matrix to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_coefficients.mat
--> Saving matrix to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_TStatistics.mat
--> Saving matrix to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_uncorrectedPValue.mat
--> Saving matrix to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_FDR.mat
--> Saving matrix to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20_correctedPValue.mat
--> Saving plot to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20TStatistics.png


/Users/nicolas.gensollen/GitRepos/POC_Stat_Pipeline/clinica_surfstat/_outputs.py:98: UserWarning: Writing results to BIDS is not implemented yet.
  warnings.warn("Writing results to BIDS is not implemented yet.")


--> Saving plot to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20uncorrectedPValue.png
--> Saving plot to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20FDR.png
--> Saving plot to out/group-UnitTest_correlation-age-positive_measure-ct_fwhm-20correctedPValue.png
########################################
After correction (Clusterwise Correction for Multiple Comparisons): 
   clusid  nverts    resels         P
0       1   135.0  2.142065  0.409476
1       2    30.0  1.788983  0.491729
2       3     6.0  0.638821  0.941232
3       4    15.0  0.048120  1.000000
4       5     1.0  0.003673  1.000000
Clusters found: 5
Significative clusters (after correction): 0
--> Computations took 127.92598509788513 seconds...
